export const result = document.getElementById('result');
export const equal = document.getElementById('equal');
export const sum = document.getElementById('sum');
export const div = document.getElementById('div');
export const mult = document.getElementById('mult');
export const sub = document.getElementById('sub');
export const full__clear = document.querySelector('.full__clear');
export const backSpace = document.querySelector('.clear__backspace');
export const numbers = document.querySelectorAll('.number__button'); // Get all buttons with numbers. It will make object. 
